version: '3.8'

services:

  nginx:
    build: requirements/nginx/.
    image: nginx_image
    ports:
      - 80:80
    restart: on-failure
    networks:
      - inception


  mariadb:
    build: requirements/mariadb/.
    image: mariadb_image
    ports:
      - 3306:3306
    restart: on-failure
    networks:
      - inception


networks:
  inception:
    name: inception
    driver: bridge