version: '3.8'

services:

  nginx:
    build: requirements/nginx/.
    image: nginx
    restart: on-failure
    ports:
      - 443:443
    volumes:
      - /Users/epfennig/Desktop/Inception/volume_test:/var/www/localhost
    networks:
      - inception

  wordpress:
    build: requirements/wordpress/.
    image: wordpress
    restart: on-failure
    ports:
      - 9000:9000
    volumes:
      - /Users/epfennig/Desktop/Inception/volume_test:/var/www/localhost
    networks:
      - inception
#    environment:
#      WORDPRESS_DB_HOST: db
#      WORDPRESS_DB_USER: exampleuser
#      WORDPRESS_DB_PASSWORD: examplepass
#      WORDPRESS_DB_NAME: exampledb
#      ALLOW_EMPTY_PASSWORD: "yes"

networks:
  inception:
    name: inception
    driver: bridge